server:
  port: 8086
  servlet:
    context-path: /booking


spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_POST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect