name: bookingstadium

services:
  kafka:
    image: 'apache/kafka:3.8.0'
    container_name: kafka
    hostname: kafka
    user: root
    ports:
      - "9094:9094"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      # === KRaft Settings ===
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      # === Listeners ===
      - KAFKA_LISTENERS=BROKER://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=BROKER://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT

      # === Cluster ID ===
      - CLUSTER_ID=nN7TCQkHS266JwTLLvtavw

      # === Topic Settings ===
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

volumes:
  kafka_data: