server:
  port: 8088
  servlet:
    context-path: /payment


spring:
  application:
    name: PaymentService

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_POST:5432}/${PAYMENT_DB_NAME:payment_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_POST:9094}
    consumer:
      group-id: payment-service-group
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest

    logging:
      level:
        org.springframework.kafka: DEBUG

jwt:
  signerKey: ${SIGNER_KEY:t3/lBrCm1lZ4HeOZtzdcgR678t3aEeFB5NVrsPSRzq4DPCRpS/D3NvbQcpMwXgKb}

momo:
  partnerCode: MOMO
  accessKey: F8BBA842ECF85
  secretKey: K951B6PE1waDMi640xX08PD3vg6EkVlz
  redirectUrl: https://yourdomain.com/payment/return
  ipnUrl: http://localhost:8088/payment/api/momo/ipn
  ipnUrlNgrok: https://85a9cadddc30.ngrok-free.app/payment/api/momo/ipn
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
