server:
  port: 8888

app:
  api-prefix: api/v1


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: ${URL_IDENTITY}
          predicates:
            - Path=/${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: profile
          uri: ${URL_PROFILE}
          predicates:
            - Path=/${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2


jwt:
  signerKey: ${SIGNER_KEY}

endpoint:
  public:
    register: /${app.api-prefix}/identity/user/register
    login: /${app.api-prefix}/identity/auth/**
