server:
  port: 8888

app:
  api-prefix: api/v1


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: ${URL_IDENTITY:http://localhost:8080}
          predicates:
            - Path=/${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: profile
          uri: ${URL_PROFILE:http://localhost:8082}
          predicates:
            - Path=/${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2

        - id: stadium
          uri: ${URL_STADIUM:http://localhost:8084}
          predicates:
            - Path=/${app.api-prefix}/stadium/**
          filters:
            - StripPrefix=2


jwt:
  signerKey: ${SIGNER_KEY:t3/lBrCm1lZ4HeOZtzdcgR678t3aEeFB5NVrsPSRzq4DPCRpS/D3NvbQcpMwXgKb}

endpoint:
  public:
    register: /${app.api-prefix}/identity/user/register
    login: /${app.api-prefix}/identity/auth/**
