server:
  port: 8084
  servlet:
    context-path: /stadium


spring:
  application:
    name: stadium-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_POST}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9094
    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: stadium-service-group
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.BookingStadium.StadiumService.dto.request.PriceRequest
      auto-offset-reset: earliest

  logging:
    level:
      org.springframework.kafka: DEBUG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: ${SIGNER_KEY}