server:
  port: 8088
  servlet:
    context-path: /payment


spring:
  application:
    name: PaymentService

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: payment-service-group
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest

    logging:
      level:
        org.springframework.kafka: DEBUG

#jwt:
#  signerKey: ${SIGNER_KEY}
