server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  application:
    name: IdentityService

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:IdentityService}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

jwt:
  signerKey: ${SIGNER_KEY}
