server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:IdentityService}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}


jwt:
  signerKey: ${SIGNER_KEY}

app:
  service:
    profile: ${URL_PROFILE}
