server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${IDENTITY_DB_NAME:IdentityService}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}


jwt:
  signerKey: ${SIGNER_KEY:t3/lBrCm1lZ4HeOZtzdcgR678t3aEeFB5NVrsPSRzq4DPCRpS/D3NvbQcpMwXgKb}

app:
  service:
    profile: ${URL_PROFILE_CREATE:http://localhost:8082/profile}
